### Create Charles Eimer
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "Charles",
  "lastName": "Eimer",
  "email": "c.eimer@email.com",
  "password": "securePass123",
  "phoneNumber": "514-555-5555"
}

### Create Sam Samson
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName": "Samson",
  "email": "ssamson@email.com",
  "password": "securePass123",
  "phoneNumber": "514-555-5555"
}

### Get Charles Eimer by ID
GET http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Accept: application/json

### Get Sam Samson by ID
GET http://localhost:8080/api/v1/users/d8e9f88e-1850-40d6-9bf1-7551979b17e8
Accept: application/json



