### Create Charles Eimer
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "Charles",
  "lastName": "Eimer",
  "email": "c.eimer@email.com",
  "password": "securePass123",
  "phoneNumber": "514-555-5555"
}

### Create Sam Samson
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName": "Samson",
  "email": "ssamson@email.com",
  "password": "securePass123",
  "phoneNumber": "514-555-5555"
}

### Get Charles Eimer by ID
GET http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Accept: application/json

### Get Sam Samson by ID
GET http://localhost:8080/api/v1/users/d8e9f88e-1850-40d6-9bf1-7551979b17e8
Accept: application/json

### Delete Sam Samson by ID
DELETE http://localhost:8080/api/v1/users/d8e9f88e-1850-40d6-9bf1-7551979b17e8
Accept: application/json

### Get All Users
GET http://localhost:8080/api/v1/users
Accept: application/json

### Update Charles Eimer to Barry White
PUT http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Content-Type: application/json

{
  "firstName": "Barry",
  "lastName": "White",
  "email": "b.white@email.com",
  "phoneNumber": "514-111-1111"
}

### Update Barry White email adress
PUT http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Content-Type: application/json

{
  "firstName": "Barry",
  "lastName": "White",
  "email": "b.white@gmail.com",
  "phoneNumber": "514-111-1111"
}

### Doesn't update Barry White given empty feilds
PUT http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "",
  "phoneNumber": ""
}

### Partial Update only to Barry White phone number
PUT http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Content-Type: application/json

{
  "phoneNumber": "514-123-4567"
}

### Partial Update only to Barry White email
PUT http://localhost:8080/api/v1/users/a6079ab3-06ff-4983-af48-78b3ee4e2962
Content-Type: application/json

{
  "email": "b.white@me.com"
}